spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/garagepi
    username: root
    password: password
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false